name: chat_app_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  uuid: ^4.3.3
  http: 0.13.6

  # ✅ Use GitHub version of flutter_webrtc to support Web with Dart 3.6+ ..  ^0.9.47
  flutter_webrtc: ^0.14.2

  provider: ^6.1.5
  socket_io_client: ^2.0.3+1
  cupertino_icons: ^1.0.8
  file_picker: ^6.1.1
  emoji_picker_flutter: ^4.3.0
  lottie: ^2.2.0
  intl: ^0.18.0
  google_sign_in: ^6.1.0
  url_launcher: ^6.2.6
  dio: ^5.3.3
  path_provider: ^2.0.15
  permission_handler: ^11.0.1
  open_file: ^3.3.2
  file_selector: ^0.9.1
  just_audio: ^0.10.4
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  video_player: ^2.10.0
  audioplayers: ^5.2.1 # or latest
  photo_view: ^0.14.0
  gallery_saver: ^2.3.2 # Optional: to save images to gallery
  open_filex: ^4.3.2
  http_parser: ^4.0.2
  mime: ^1.0.4
  shared_preferences: ^2.2.2
  contacts_service: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
